name: Playwright Tests
on:
  push:
    branches: [ main, master, feature/* ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      # This is where we inject the secrets from GitHub Settings into the Runner
      run: npx playwright test
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        Valid_AdminUserName: ${{ secrets.ADMIN_USER }}
        Valid_AdminPassword: ${{ secrets.ADMIN_PASS }}
        InValid_AdminUserName: ${{ secrets.INVALID_ADMINUSERNAME }}
        InValid_AdminPassword: ${{ secrets.INVALID_ADMINPASSWORD }}
        
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Get Playwright version
      id: playwright-version
      run: echo "version=$(npm ls @playwright/test --json | jq -r '.dependencies["@playwright/test"].version')" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Install Playwright Dependencies (if cache hit)
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps